apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-k8s
  template:
    metadata:
      labels:
        app: server-k8s
    spec:
      containers:
      - name: server-k8s
        image: jaycynth/server-k8s:v0.1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: server-k8s
spec:
  selector:
    app: server-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
