- name: Install etcd
  shell: |
    wget -q --show-progress --https-only --timestamping "https://github.com/etcd-io/etcd/releases/latest/download/etcd-linux-amd64.tar.gz"
    tar -xvf etcd-linux-amd64.tar.gz
    sudo mv etcd etcdctl /usr/local/bin/
  args:
    creates: /usr/local/bin/etcd

- name: Configure etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Enable and start etcd
  systemd:
    name: etcd
    enabled: yes
    state: started
