---
- hosts: all
  become: yes
  tasks:
    - name: Install k0s
      shell: |
        curl -sSLf https://get.k0s.sh | sudo sh

    - name: Configure Master Nodes
      when: "inventory_hostname in groups['master']"
      shell: |
        sudo k0s install controller
        sudo k0s start
        sudo k0s token create --role worker > /tmp/k0s_worker_token

    - name: Retrieve Worker Token
      when: "inventory_hostname in groups['worker']"
      copy:
        src: /tmp/k0s_worker_token
        dest: /tmp/k0s_worker_token
      delegate_to: "{{ groups['master'][0] }}"

    - name: Configure Worker Nodes
      when: "inventory_hostname in groups['worker']"
      shell: |
        sudo k0s install worker --token-file /tmp/k0s_worker_token
        sudo k0s start
