- hosts: masters
  become: yes
  tasks:
    - name: Install k3s on master nodes
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
      environment:
        K3S_KUBECONFIG_MODE: "644"

- hosts: workers
  become: yes
  tasks:
    - name: Retrieve the token from the first master node
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      delegate_to: master-node-1

    - name: Install k3s on worker nodes
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://master-node-1:6443 K3S_TOKEN={{ k3s_token.stdout }} sh -
      environment:
        K3S_KUBECONFIG_MODE: "644"
